using System.Security.Cryptography;
using System.Text.Json;
using WinBridge.Core.Protocol;

namespace WinBridge.Core.Tests;

/// <summary>
/// Emits known-answer vectors for the Kotlin implementation to assert against.
///
/// Three cross-language mistakes all surface identically as "server failed
/// authentication" over a socket — a mis-padded 32-byte coordinate, a hashed
/// instead of raw ECDH agreement, and an HKDF that differs. Pinning Z, the
/// transcript, each derived key and one sealed frame makes each of them fail in
/// its own place, locally, in milliseconds.
/// </summary>
public static class Vectors
{
    public static void Emit(string outputPath)
    {
        // Fixed key material. These were generated once and then frozen here:
        // regenerating them on every run made the file change every time, which
        // turned the CI check that compares committed vectors against freshly
        // generated ones into a guaranteed failure and hid real drift behind
        // noise. Known-answer vectors have to be, in fact, known.
        using var client = LoadKey(ClientPrivate, ClientPublicPoint);
        using var server = LoadKey(ServerPrivate, ServerPublicPoint);

        var clientParams = client.ExportParameters(true);
        var serverParams = server.ExportParameters(true);

        byte[] clientPub = ProtocolSession.ExportPoint(client);
        byte[] serverPub = ProtocolSession.ExportPoint(server);

        byte[] nonceClient = Enumerable.Range(0, 16).Select(i => (byte)(0x10 + i)).ToArray();
        byte[] nonceServer = Enumerable.Range(0, 16).Select(i => (byte)(0xA0 + i)).ToArray();
        byte[] psk = Enumerable.Range(0, 32).Select(i => (byte)(i * 7 + 1)).ToArray();

        const string clientId = "11111111-1111-4111-8111-111111111111";
        const string serverId = "22222222-2222-4222-8222-222222222222";

        byte[] transcript = ProtocolSession.ComputeTranscript(
            clientId, clientPub, nonceClient,
            serverId, serverPub, nonceServer);

        var schedule = CryptoBox.ComputeSchedule(
            client, serverPub, nonceClient, nonceServer, psk, transcript);

        // Sanity: the server must land on the same schedule from its own side.
        var mirror = CryptoBox.ComputeSchedule(
            server, clientPub, nonceClient, nonceServer, psk, transcript);
        if (!mirror.Z.AsSpan().SequenceEqual(schedule.Z))
            throw new Exception("the two sides disagree about Z; vectors would be meaningless");

        // One sealed frame, produced by the client's send direction at counter 1.
        using var clientBox = CryptoBox.Derive(
            client, serverPub, nonceClient, nonceServer, psk, transcript, isServer: false);
        byte[] plaintext = "{\"t\":\"ping\",\"echo\":42}"u8.ToArray();
        byte[] sealedFrame = clientBox.Seal(plaintext);

        var vectors = new
        {
            note = "WinBridge protocol v1 known-answer vectors. Generated by WinBridge.Core.Tests --vectors.",
            clientDeviceId = clientId,
            serverDeviceId = serverId,
            clientPrivate = Hex(Pad32(clientParams.D!)),
            clientPublicPoint = Hex(clientPub),
            serverPrivate = Hex(Pad32(serverParams.D!)),
            serverPublicPoint = Hex(serverPub),
            nonceClient = Hex(nonceClient),
            nonceServer = Hex(nonceServer),
            psk = Hex(psk),
            expected = new
            {
                z = Hex(schedule.Z),
                transcript = Hex(transcript),
                keyC2S = Hex(schedule.KeyC2S),
                keyS2C = Hex(schedule.KeyS2C),
                noncePrefixC2S = Hex(schedule.NonceC2S),
                noncePrefixS2C = Hex(schedule.NonceS2C),
                confirmServer = Hex(schedule.ConfirmServer),
                confirmClient = Hex(schedule.ConfirmClient),
                sealedCounter = 1,
                sealedPlaintext = Hex(plaintext),
                sealedFrame = Hex(sealedFrame),
            },
            messagesV2 = SampleMessages(),
        };

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath,
            JsonSerializer.Serialize(vectors, new JsonSerializerOptions { WriteIndented = true }));

        Console.WriteLine($"wrote vectors to {outputPath}");
    }

    /// <summary>
    /// .NET already gives fixed-width curve parameters, but this makes the
    /// invariant explicit — a 31- or 33-byte scalar is exactly the bug these
    /// vectors exist to catch on the other side.
    /// </summary>
    private static byte[] Pad32(byte[] value)
    {
        if (value.Length == 32) return value;
        var padded = new byte[32];
        value.CopyTo(padded, 32 - value.Length);
        return padded;
    }

    private static string Hex(byte[] data) => Convert.ToHexString(data).ToLowerInvariant();

    // P-256 scalars and their matching public points. Frozen, not generated.
    private const string ClientPrivate =
        "0d75e7872913836936176ea47626ffadc5bc7357256f5309679c6b18baedac3a";
    private const string ClientPublicPoint =
        "04e1ce9f9d66c7c411fcd265c8c39bfbee4f6509726d69613d2cac8cb071fac3a5" +
        "54b3dc2dc04797a1180163a76c22aa6b7a61a68b8c4eee76ad146f69b9e43667";
    private const string ServerPrivate =
        "20950aba2a5d0df2d01cc9e016dd103dd7c3493a128caa78e7863fb603f014eb";
    private const string ServerPublicPoint =
        "046da818ed66ba889044af2faa4787a98de89064f3d04d0009c38645497b937bf7" +
        "0c4f92cd69fe7b75e582b1c56f14505ae42b543723633fb84adb53ba6e30d645";

    /// <summary>
    /// Rebuilds a key pair from a frozen scalar and its uncompressed point.
    /// .NET will not derive Q from D on import, so the point is stored alongside
    /// and checked against the curve when the key is created.
    /// </summary>
    private static ECDiffieHellman LoadKey(string privateHex, string pointHex)
    {
        byte[] d = Convert.FromHexString(privateHex);
        byte[] point = Convert.FromHexString(pointHex);
        if (point.Length != 65 || point[0] != 0x04)
            throw new Exception("expected an uncompressed 65-byte P-256 point");

        return ECDiffieHellman.Create(new ECParameters
        {
            Curve = ECCurve.NamedCurves.nistP256,
            D = d,
            Q = new ECPoint { X = point[1..33], Y = point[33..65] },
        });
    }

    /// <summary>
    /// One filled-in sample of every v2 message, serialised by the C# models.
    /// The Kotlin side decodes these in `MessagesV2Test`, which is what catches
    /// a renamed JSON property before it turns into a field that silently
    /// arrives as its default on the other side — the failure mode that is
    /// almost impossible to spot from a log.
    /// </summary>
    private static Dictionary<string, JsonElement> SampleMessages()
    {
        var samples = new List<object>
        {
            new FeatureSet
            {
                Clipboard = new ClipboardCaps { Send = true, Receive = true, MaxBytes = 1024 },
                Files = new FileCaps { Enabled = true, MaxChunk = 32768, AutoAccept = true },
                Screen = new ScreenCaps { Send = true, Receive = false, Targets = 2, CarrierOk = false },
                Audio = new AudioCaps { Playback = true, Mic = true },
                Input = new InputCaps { Send = true, Receive = true, Reason = "ok" },
                Automations = true, Shell = true, Notifications = true, Describe = true, Ring = true,
            },
            new ClipboardMessage { Format = "text", Text = "merhaba", Hash = "abc123", Label = "PC" },
            new ClipboardRequest(),
            new XferOffer
            {
                Id = 9, Name = "notes.txt", Size = 4096, Mime = "text/plain", Sha256 = "ff00",
                Batch = 3, BatchIndex = 1, BatchCount = 2, Path = "sub/notes.txt",
            },
            new XferAccept { Id = 9, Offset = 1024 },
            new XferReject { Id = 9, Reason = "declined" },
            new XferProgress { Id = 9, Bytes = 2048, BytesPerSecond = 999 },
            new XferDone { Id = 9, Ok = true, Sha256 = "ff00", SavedAs = "C:/x/notes.txt" },
            new XferCancel { Id = 9, Reason = "user" },
            new ScreenTargets
            {
                Items = [new ScreenTarget { Id = "m0", Name = "Monitor 1", Kind = "monitor", Width = 1920, Height = 1080, Primary = true }],
            },
            new ScreenListRequest(),
            new StreamStart
            {
                Stream = "pc.screen", Codec = "jpeg-tiles", MaxFps = 45, Quality = 55,
                MaxEdge = 1600, Target = "m0", Audio = true, Interact = true, Cursor = false,
            },
            new StreamStop { Stream = "pc.screen" },
            new StreamInfo
            {
                Stream = "pc.screen", Active = true, Width = 1600, Height = 900, TileWidth = 64,
                TileHeight = 64, Columns = 25, Rows = 15, Target = "m0", Interact = true, Reason = null,
            },
            new StreamConfig { Stream = "pc.screen", MaxFps = 20, Quality = 40, MaxEdge = 800, Interact = false, Cursor = true },
            new StreamStats { Stream = "pc.screen", Fps = 28.5, Kbps = 3200.25, RttMs = 14, DecodeMs = 3.5, Dropped = 7, LatencyMs = 55 },
            new AudioStart { Stream = "pc.audio", Rate = 44100, Channels = 1, FrameMs = 40, Device = "dev1" },
            new AudioStop { Stream = "pc.audio" },
            new AudioInfo { Stream = "pc.audio", Active = true, Rate = 44100, Channels = 1, FrameMs = 40, Device = "dev1" },
            new AudioDevices { Items = [new AudioDevice { Id = "dev1", Name = "Speakers", Flow = "render", IsDefault = true }] },
            new AudioRoute { Stream = "pc.audio", Device = "dev1" },
            new InputMouse { Action = "wheel", X = 0.25, Y = 0.75, Button = "middle", Delta = -120, HorizontalDelta = 3, Dx = 0.01, Dy = -0.02, Relative = true },
            new InputKey { Action = "tap", Code = "f5", Mods = ["ctrl", "shift"], Repeat = 2 },
            new InputText { Text = "gunaydin" },
            new InputTouch { Action = "move", Pointer = 1, X = 0.5, Y = 0.5, Pressure = 0.8 },
            new InputGesture
            {
                Kind = "swipe", DurationMs = 200,
                Points = [new GesturePoint { X = 0.1, Y = 0.2, AtMs = 0 }, new GesturePoint { X = 0.8, Y = 0.2, AtMs = 200 }],
                Points2 = [new GesturePoint { X = 0.9, Y = 0.9, AtMs = 0 }],
            },
            new InputNav { Action = "recents" },
            new InputScroll { X = 0.5, Y = 0.5, Dx = 0, Dy = -0.1 },
            new NotifPost
            {
                Key = "k1", Package = "com.x", AppName = "X", Title = "Title", Text = "Body",
                SubText = "sub", BigText = "big", When = 1700000000000, Ongoing = true,
                Category = "msg", IconHash = "deadbeef",
                Actions = [new NotifAction { Index = 0, Title = "Reply", IsReply = true }],
            },
            new NotifRemove { Key = "k1" },
            new NotifActionCommand { Key = "k1", Index = 0, Text = "tamam" },
            new NotifDismiss { Key = "k1" },
            new NotifSync(),
            new NotifState { Enabled = true, Granted = false, Count = 3, Reason = "no access" },
            new WindowList { Items = [new WindowInfo { Handle = 123, Title = "Notepad", Process = "notepad", Pid = 42, Active = true, Minimized = false }] },
            new WindowsRequest(),
            new WindowCommand { Action = "focus", Handle = 123, Match = "Notepad" },
            new ProcessList { Items = [new ProcessInfo { Pid = 42, Name = "notepad", MemoryMb = 64, Cpu = 1.5 }] },
            new ProcessesRequest { Top = 10 },
            new ProcessCommand { Action = "kill", Pid = 42 },
            new DescribeRequest { Target = "m0", Ocr = true, Image = true },
            new Description { Title = "Notepad", Process = "notepad", Text = "hello", Windows = ["a", "b"], Width = 800, Height = 600, ImageHash = "cafe" },
            new SysNotify { Title = "Hi", Text = "There", Level = "warn" },
            new SysOpen { Target = "https://example.invalid" },
            new PhoneRing { Action = "start", Seconds = 15 },
            new PhoneState { Model = "Redmi", Battery = 55, Charging = true, Ringer = "normal", Network = "wifi", Volume = 7, ScreenOn = true },
            new AutoListRequest(),
            SampleCatalog(),
            new AutoGetRequest { Id = "a1" },
            new AutoDefinition { Automation = SampleAutomation() },
            new AutoSaveRequest { Automation = SampleAutomation() },
            new AutoSaved { Id = "a1", State = "pending", Reason = "needs approval", Summary = SampleSummary() },
            new AutoDeleteRequest { Id = "a1" },
            new AutoRunRequest { Id = "a1", Args = new Dictionary<string, string> { ["who"] = "world" }, DryRun = true },
            new AutoEvent { RunId = "r1", AutomationId = "a1", Phase = "step", StepIndex = 2, StepId = "s2", StepType = "shell", Level = "warn", Message = "slow", At = 1700000000000 },
            new AutoResult { RunId = "r1", AutomationId = "a1", Ok = true, Output = "done", StepsRun = 4, DurationMs = 1234, Variables = new Dictionary<string, string> { ["x"] = "1" } },
            new AutoCancelRequest { RunId = "r1" },
            new AutoLog { Items = [new AutoLogEntry { At = DateTimeOffset.UnixEpoch, AutomationId = "a1", Name = "Focus", Device = "phone", Ok = true, DurationMs = 12, Detail = "ok" }] },
        };

        var result = new Dictionary<string, JsonElement>();
        foreach (var sample in samples)
        {
            // The runtime type matters: Json.Serialize<T> would otherwise write
            // only the properties visible on object.
            byte[] utf8 = JsonSerializer.SerializeToUtf8Bytes(sample, sample.GetType(), Json.Options);
            var element = JsonSerializer.Deserialize<JsonElement>(utf8);
            string name = element.GetProperty("t").GetString()!;
            result[name] = element;
        }
        return result;
    }

    private static Automation SampleAutomation() => new()
    {
        Id = "a1",
        Name = "Focus Chrome",
        Description = "Bring Chrome forward and say hello",
        Icon = "bolt",
        Color = "#3366ff",
        Enabled = true,
        ConfirmEachRun = true,
        RequireUnlocked = true,
        CreatedBy = "phone-1",
        CreatedAt = DateTimeOffset.UnixEpoch,
        UpdatedAt = DateTimeOffset.UnixEpoch,
        Approved = true,
        BodyHash = "hash1",
        Risk = "shell",
        Shortcut = "focus-chrome",
        Variables = new Dictionary<string, string> { ["who"] = "world" },
        Steps =
        [
            new AutoStep
            {
                Id = "s1", Type = StepTypes.Window, Action = "focus",
                Target = "Chrome", Note = "bring it forward",
            },
            new AutoStep
            {
                Id = "s2", Type = StepTypes.If, Condition = "battery < 20",
                Then = [new AutoStep { Id = "s3", Type = StepTypes.Notify, Text = "low battery" }],
                Else = [new AutoStep { Id = "s4", Type = StepTypes.Delay, Number = 250 }],
            },
            new AutoStep
            {
                Id = "s5", Type = StepTypes.ForEach, Items = "split(list, \",\")", Var = "item",
                Do = [new AutoStep { Id = "s6", Type = StepTypes.Log, Text = "{{item}}" }],
            },
            new AutoStep
            {
                Id = "s7", Type = StepTypes.Shell, Shell = "powershell",
                Command = "Write-Output {{who}}", Args = ["-NoProfile"],
                WorkingDirectory = "C:/", TimeoutMs = 5000, Elevated = false,
                Hidden = true, Capture = true, OnErrorContinue = true,
            },
            new AutoStep
            {
                Id = "s8", Type = StepTypes.Http, Url = "https://example.invalid", Method = "POST",
                Headers = new Dictionary<string, string> { ["X-A"] = "b" }, Body = "{}",
            },
        ],
    };

    private static AutomationSummary SampleSummary() => new()
    {
        Id = "a1", Name = "Focus Chrome", Description = "d", Icon = "bolt", Color = "#3366ff",
        Enabled = true, Approved = true, ConfirmEachRun = true, StepCount = 5, Risk = "shell",
        UpdatedAt = DateTimeOffset.UnixEpoch,
    };

    private static AutoCatalog SampleCatalog() => new()
    {
        Items = [SampleSummary()],
        StepTypes = [.. Protocol.StepTypes.All],
        ShellEnabled = true,
        TrustMode = "trusted",
        DeviceTrusted = true,
        AuthoringAllowed = true,
        Allowlist = ["notepad.exe"],
        Functions = ["contains", "len"],
        Variables = ["cpu", "battery"],
    };
}
