using System.Security.Cryptography;
using System.Text.Json;
using WinBridge.Core.Protocol;

namespace WinBridge.Core.Tests;

/// <summary>
/// Emits known-answer vectors for the Kotlin implementation to assert against.
///
/// Three cross-language mistakes all surface identically as "server failed
/// authentication" over a socket — a mis-padded 32-byte coordinate, a hashed
/// instead of raw ECDH agreement, and an HKDF that differs. Pinning Z, the
/// transcript, each derived key and one sealed frame makes each of them fail in
/// its own place, locally, in milliseconds.
/// </summary>
public static class Vectors
{
    public static void Emit(string outputPath)
    {
        // Deterministic inputs. The private scalars are generated once and then
        // written into the vector file itself, so both sides start from exactly
        // the same key material.
        using var client = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
        using var server = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);

        var clientParams = client.ExportParameters(true);
        var serverParams = server.ExportParameters(true);

        byte[] clientPub = ProtocolSession.ExportPoint(client);
        byte[] serverPub = ProtocolSession.ExportPoint(server);

        byte[] nonceClient = Enumerable.Range(0, 16).Select(i => (byte)(0x10 + i)).ToArray();
        byte[] nonceServer = Enumerable.Range(0, 16).Select(i => (byte)(0xA0 + i)).ToArray();
        byte[] psk = Enumerable.Range(0, 32).Select(i => (byte)(i * 7 + 1)).ToArray();

        const string clientId = "11111111-1111-4111-8111-111111111111";
        const string serverId = "22222222-2222-4222-8222-222222222222";

        byte[] transcript = ProtocolSession.ComputeTranscript(
            clientId, clientPub, nonceClient,
            serverId, serverPub, nonceServer);

        var schedule = CryptoBox.ComputeSchedule(
            client, serverPub, nonceClient, nonceServer, psk, transcript);

        // Sanity: the server must land on the same schedule from its own side.
        var mirror = CryptoBox.ComputeSchedule(
            server, clientPub, nonceClient, nonceServer, psk, transcript);
        if (!mirror.Z.AsSpan().SequenceEqual(schedule.Z))
            throw new Exception("the two sides disagree about Z; vectors would be meaningless");

        // One sealed frame, produced by the client's send direction at counter 1.
        using var clientBox = CryptoBox.Derive(
            client, serverPub, nonceClient, nonceServer, psk, transcript, isServer: false);
        byte[] plaintext = "{\"t\":\"ping\",\"echo\":42}"u8.ToArray();
        byte[] sealedFrame = clientBox.Seal(plaintext);

        var vectors = new
        {
            note = "WinBridge protocol v1 known-answer vectors. Generated by WinBridge.Core.Tests --vectors.",
            clientDeviceId = clientId,
            serverDeviceId = serverId,
            clientPrivate = Hex(Pad32(clientParams.D!)),
            clientPublicPoint = Hex(clientPub),
            serverPrivate = Hex(Pad32(serverParams.D!)),
            serverPublicPoint = Hex(serverPub),
            nonceClient = Hex(nonceClient),
            nonceServer = Hex(nonceServer),
            psk = Hex(psk),
            expected = new
            {
                z = Hex(schedule.Z),
                transcript = Hex(transcript),
                keyC2S = Hex(schedule.KeyC2S),
                keyS2C = Hex(schedule.KeyS2C),
                noncePrefixC2S = Hex(schedule.NonceC2S),
                noncePrefixS2C = Hex(schedule.NonceS2C),
                confirmServer = Hex(schedule.ConfirmServer),
                confirmClient = Hex(schedule.ConfirmClient),
                sealedCounter = 1,
                sealedPlaintext = Hex(plaintext),
                sealedFrame = Hex(sealedFrame),
            },
        };

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath,
            JsonSerializer.Serialize(vectors, new JsonSerializerOptions { WriteIndented = true }));

        Console.WriteLine($"wrote vectors to {outputPath}");
    }

    /// <summary>
    /// .NET already gives fixed-width curve parameters, but this makes the
    /// invariant explicit — a 31- or 33-byte scalar is exactly the bug these
    /// vectors exist to catch on the other side.
    /// </summary>
    private static byte[] Pad32(byte[] value)
    {
        if (value.Length == 32) return value;
        var padded = new byte[32];
        value.CopyTo(padded, 32 - value.Length);
        return padded;
    }

    private static string Hex(byte[] data) => Convert.ToHexString(data).ToLowerInvariant();
}
